trigger:
  branches:
    include:
      - master  # Adjust as per your branch structure

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'

stages:
  - stage: Build_and_Test
    jobs:
      - job: Build
        steps:
          
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean install'
          
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'test -P smoke -Dsurefire.suiteXmlFiles=testng.xml'

      - job: Publish
        dependsOn: Build
        steps:
          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/surefire-reports/*.xml'
              failTaskOnFailedTests: true
          